version: '3.9'

services:
  # ==========================================================
  # 🗄️ SQL SERVER 2022
  # ==========================================================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123.
      - MSSQL_PID=Developer
    ports:
      - "1439:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - databases-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ==========================================================
  # 🗄️ POSTGRESQL 16
  # ==========================================================
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123.
      - POSTGRES_DB=app_database
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - databases-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ==========================================================
  # 🗄️ MYSQL 8.0
  # ==========================================================
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123.
      - MYSQL_DATABASE=app_database
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=apppass
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - databases-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

# ==========================================================
# 📦 Volúmenes persistentes
# ==========================================================
volumes:
  sqlserver_data:
  postgres_data:
  mysql_data:

# ==========================================================
# 🌐 Red interna compartida
# ==========================================================
networks:
  databases-net:
    driver: bridge
